# We define the interval for the updates to be monthly
# because we don't want to have too many updates
# and the project is currently in a development stage

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: meta
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: monthly
    commit-message:
      prefix: meta
    groups:
      fromat:
        patterns:
          - 'prettier'
      lint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'globals'
          - 'stylelint-*'
    open-pull-requests-limit: 10
