coverage:
  # https://docs.codecov.com/docs/commit-status
  status:
    patch: false
    project:
      default:
        # TODO(@avivkeller): Once our coverage > 70%,
        # increase this to 70%, and increase on increments
        target: 60%

ignore:
  - 'eslint.config.mjs'
  - '**/fixtures/'
